# Generated by Django 4.2.1 on 2025-11-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
