# Generated by Django 4.2.1 on 2025-11-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_question_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
    ]
