# Generated by Django 4.2.1 on 2025-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_question_count_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-time_create'], name='main_app_qu_time_cr_762a52_idx'),
        ),
    ]
