# Generated by Django 4.2.1 on 2025-11-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_question_options_question_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='count_answers',
        ),
    ]
