# Generated by Django 4.2.1 on 2025-11-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
