# Generated by Django 4.2.1 on 2025-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_question_id_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.CharField(default='Гость', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default='Гость', max_length=20),
        ),
    ]
