# Generated by Django 4.2.1 on 2025-11-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_answer_user_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.CharField(db_index=True, default='Гость', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.CharField(db_index=True, default='Гость', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main_app.tagquestion'),
        ),
    ]
